#!/bin/bash

SCRIPT_DIR=$(dirname "$(realpath "$0")")
FILENAME="$SCRIPT_DIR/pkgorder/perl-order.txt"

if [ ! -f "$FILENAME" ]; then
    echo "Error: File '$FILENAME' not found!"
    exit 1
fi

while IFS= read -r line; do
    $SCRIPT_DIR/alpine-package-sync $line -no
done < "$FILENAME"
