#!/bin/sh

export QT_WAYLAND_SHELL_INTEGRATION=qt-shell
doas hollywood-setup
if [ $? -eq 0 ]; then
	doas hollywood-setup-run
	export QT_WAYLAND_SHELL_INTEGRATION=xdg-shell
	doas hwsettings --single org.originull.hwsettings.startup
fi
